# <center> <u>**Resnet 50 avec politique de batch uniformément réparti** </u></center>



# 1. Import des données


In [1]:
import os 
import pandas as pd
import numpy as np
import keras
import tensorflow as tf
from sklearn.datasets import load_files

2023-07-04 10:08:04.536855: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-07-04 10:08:04.894579: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
# main folder
path_to_folder = '../data_bees_detection/dataset_classification'

classes = os.listdir(os.path.join(path_to_folder, 'train'))
nb_classes = len(classes)  

# function to load a split of the dataset
def load_dataset(path):
    data = load_files(path)
    target_files = np.array(data['filenames'])
    target_labels = keras.utils.to_categorical(np.array(data['target']), nb_classes)
    return target_files, target_labels

# load the datasets
train_files, train_labels = load_dataset(os.path.join(path_to_folder, 'train'))
valid_files, valid_labels = load_dataset(os.path.join(path_to_folder, 'validation'))
test_files, test_labels = load_dataset(os.path.join(path_to_folder, 'test'))

Définition de l'augmentation et de la normalisation

In [3]:
# def function to augment the images
import cv2 
from PIL import Image
import albumentations as A
from albumentations import (Compose, Rotate, HorizontalFlip, VerticalFlip, Affine, RandomBrightnessContrast, ChannelShuffle)
import albumentations as A

AUGMENTATIONS = Compose([
    Rotate(limit=[0,100], p=0.5),
    HorizontalFlip(p=0.5),
    VerticalFlip(p=0.5),
    Affine(shear=[-45, 45], p=0.5),
])


In [4]:
# Batch generator

from keras.preprocessing import image
from keras.applications.resnet import preprocess_input
from keras.utils import Sequence
from keras.utils import load_img, img_to_array



def path_to_tensor(img_path):
    # loads RGB image as PIL.Image.Image type
    img = image.load_img(img_path, target_size=(224, 224))
    # convert PIL.Image.Image type to 3D tensor with shape (224, 224, 3)
    x = image.img_to_array(img)
    # convert 3D tensor to 4D tensor with shape (1, 224, 224, 3) and return 4D tensor
    return preprocess_input(np.expand_dims(x, axis=0))

class BatchGenerator(Sequence):

    def __init__(self, paths, labels, batch_size, augmentations,normalize=None):


        self.paths = paths
        self.labels = labels
        self.batch_size = batch_size
        self.augment = augmentations
        self.normalize = normalize
      
        self.num_classes = np.unique(self.labels).shape[0]
        self.min_class_count = min(np.unique(self.labels, return_counts=True)[1])


        # get class indices
        class_indices = []
        for i in range(self.num_classes):
            class_indices.append(np.where(self.labels == i)[0])
        self.class_indices = class_indices

        # shuffle indices at the beginning of first epoch
        self.on_epoch_end()



    def __len__(self):
        # nb of batches per epoch
        return int(np.ceil(len(self.paths) / float(self.batch_size)))
    
    def load_img(self, img_path):

        # loads img 
        img = load_img(img_path, target_size=(224,224))
        x = img_to_array(img)
        
        # convert 3D tensor to 4D tensor with shape (1, 224, 224, 3) and return 4D tensor
        x =  np.expand_dims(x, axis=0)
        x = preprocess_input(x)
        return x

    def apply_augmentation(self, batch_imgs):
        # apply augmentation to a batch of images

        batch_imgs = batch_imgs.astype(np.uint8)
        

        for i in range(len(batch_imgs)):
            batch_imgs[i] = self.augment(image=batch_imgs[i])['image']

        return batch_imgs
    
    def normalize_batch(self, batch_imgs):
        # normalize a batch of images

        batch_imgs = batch_imgs.astype(np.float32)

        # normalize with imagenet stats
        mean = [125.3, 123.0, 113.9]
        std  = [63.0,  62.1,  66.7]

        for i in range(len(batch_imgs)):
            batch_imgs[i] -= mean
            batch_imgs[i] /= std

        return batch_imgs
        


    def __getitem__(self, idx):
        # get batch at position index

        indices = self.indices[idx * self.batch_size:(idx + 1) * self.batch_size]
        batch_paths = self.paths[indices]
        batch_labels = self.labels[indices]

        batch_imgs = np.zeros((len(batch_paths), 224, 224, 3))
        for i, f in enumerate(batch_paths):
            batch_imgs[i] = self.load_img(f)

        if self.augment: 
            batch_imgs = self.apply_augmentation(batch_imgs)

        if self.normalize:
            batch_imgs = self.normalize_batch(batch_imgs)
            
        return batch_imgs, batch_labels
    


    def on_epoch_end(self):

        balanced_indices = []

        for indices in self.class_indices:
            if len(indices) > self.min_class_count:
                indices = np.random.choice(indices, size=self.min_class_count, replace=True)
            balanced_indices.extend(indices)

        self.indices = np.array(balanced_indices)

        print(self.indices)

        np.random.shuffle(self.indices)



In [5]:
ds_train = BatchGenerator(train_files, train_labels, 16, False,False)
ds_valid = BatchGenerator(valid_files, valid_labels, 16,  False,False)
ds_test = BatchGenerator(test_files, test_labels, 16,  False,False)

[41280 32723 19038 ... 59442 59443 59444]
[12174  7051 10644 ... 15323 15324 15325]
[ 7975  7296   542 ... 19114 19115 19116]


# 2. Choix de l'architecture du modèle, des paramètres et hyperparamètres

In [6]:
from keras.applications.resnet import ResNet50
from keras.models import Model
from keras.layers import Dense, GlobalAveragePooling2D, Dropout

# we take resnet50 as convolutional base with weights trained on imagenet
base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

# we add the classification layers
x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dense(1024, activation='relu')(x)
x = Dropout(0.5)(x)
predictions = Dense(nb_classes, activation='softmax')(x)

# we create the final model
model = Model(inputs=base_model.input, outputs=predictions)


2023-07-04 10:08:48.248055: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-07-04 10:08:48.283958: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-07-04 10:08:48.284761: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysf

In [7]:
from keras.optimizers import Adam

opti = Adam(learning_rate=0.0001)
metrics = [tf.keras.metrics.CategoricalAccuracy(), tf.keras.metrics.Precision(), tf.keras.metrics.Recall()]
model.compile(optimizer=opti, loss='categorical_crossentropy', metrics=metrics)


In [8]:
# add callbacks
from keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau

# checkpoint to save the best model
path_to_weights = '/datafiles/classification/saved_weights/benchmark_weights/3_resnet_batch_capped.h5'
checkpoint = ModelCheckpoint(filepath=path_to_weights, monitor='val_categorical_accuracy', save_best_only=True, save_weights_only=False)

# early stopping
early_stopping = EarlyStopping(monitor='val_categorical_accuracy', patience=10)

# reduce learning rate
reduce_lr = ReduceLROnPlateau(monitor='val_categorical_accuracy', factor=0.1, patience=5, min_lr=0.00001)

In [9]:
model.load_weights(path_to_weights)

# 3. Entrainement du modèle

In [10]:
history = model.fit(ds_train, epochs=100, validation_data=ds_valid, callbacks=[checkpoint, early_stopping, reduce_lr])

Epoch 1/100


2023-07-04 10:08:54.856833: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]
2023-07-04 10:09:06.072993: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:424] Loaded cuDNN version 8600
2023-07-04 10:09:09.032009: W tensorflow/tsl/framework/bfc_allocator.cc:296] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.14GiB with freed_by_count=0. The caller indicates that this is not a failure, but this may mean that there could be performance gains if more memory were available.
2023-07-04 10:09:09.423840: W tensorflow/tsl/framework/bfc_allocator.cc:296] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.27GiB with freed_by_count=0. The caller indicates that this is not a failure, but this may mean that there could be

3716/3716 [==============================] - ETA: 0s - loss: 0.2445 - categorical_accuracy: 0.9266 - precision: 0.9483 - recall: 0.9086

2023-07-04 10:29:54.097731: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]


[ 1494  7427  8205 ... 15323 15324 15325]
